# Generated by Django 4.1.7 on 2023-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('postion', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('startdate', models.DateTimeField(null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
