# Generated by Django 4.1.7 on 2023-04-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Zipcode', models.IntegerField(null=True)),
                ('Phonenumber', models.IntegerField(null=True)),
                ('Webadress', models.DateField(null=True)),
                ('Emailaddress', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
