# Generated by Django 4.1.7 on 2023-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_add_venue_alter_employee_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.IntegerField(max_length=20)),
                ('Title', models.CharField(max_length=20)),
                ('Text', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(null=True)),
                ('Published_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='add_venue',
            name='Webadress',
            field=models.IntegerField(null=True),
        ),
    ]
